# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.3.3
_src_path: https://github.com/hmiladhia/package-template
distribution_name: pylazyimports
github_user: hmiladhia
is_multi_package: true
license: mit
linting_level: 2
package_name: lazyimports
project_description: A module to enable lazy imports using native python syntax
project_name: lazyimports
project_version: 0.5.0
publish_condition: push
use_commitizen: true
use_mypy: true
use_precommit: true
use_tox: true
user_email: ''
user_name: Dhia Hmila
