name: 🚀 Upload Python Package to PYPI
permissions: {}

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  quality:
    name: 🚧 Quality Gates
    uses: ./.github/workflows/quality.yml

  publish:
    name: 🚀 Upload Python Package to PYPI
    runs-on: ubuntu-latest
    needs: [quality]
    environment:
      name: pypi

    permissions:
      id-token: write

    steps:
      - name: 🔍 Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 🧰 Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: "true"

      - name: 🔨 Build packages
        run: uv build --all


      - name: 🚀 Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
